import { StyleSheet } from "react-native";

import { THEME } from "./theme";

export const ui = StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, padding: 16, backgroundColor: THEME.mint },
  page: { padding: 16, gap: 12, backgroundColor: THEME.mint },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  title: {
    color: THEME.darkGreen,
    fontSize: 28,
    fontWeight: "700",
    fontFamily: "Georgia",
  },
  muted: { color: THEME.muted, lineHeight: 20 },
  label: { color: THEME.darkGreen, fontWeight: "600", marginTop: 8 },
  input: {
    backgroundColor: THEME.white,
    borderColor: THEME.line,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    color: THEME.darkGreen,
    marginBottom: 8,
  },
  inputDisabled: {
    backgroundColor: THEME.disabledFill,
    color: THEME.disabledText,
  },
  multiline: { minHeight: 72, textAlignVertical: "top" },
  button: {
    backgroundColor: THEME.darkGreen,
    minHeight: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  buttonDisabled: { opacity: 0.45 },
  buttonLabel: { color: THEME.white, fontWeight: "700" },
  secondary: {
    borderColor: THEME.darkGreen,
    borderWidth: 1,
    minHeight: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: THEME.white,
  },
  secondaryLabel: { color: THEME.darkGreen, fontWeight: "700" },
  danger: {
    backgroundColor: "#8e1f0b",
    minHeight: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  link: { color: THEME.darkGreen, fontWeight: "600" },
  error: { color: "#8e1f0b" },
  card: {
    backgroundColor: THEME.white,
    borderColor: THEME.line,
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  cardTitle: { color: THEME.darkGreen, fontWeight: "700", fontSize: 16 },
  cardMeta: { color: THEME.darkGreen, marginTop: 4 },
  row: { flexDirection: "row", gap: 8 },
  flexItem: { flex: 1 },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: THEME.line,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: THEME.white,
  },
  chipOn: { backgroundColor: THEME.darkGreen, borderColor: THEME.darkGreen },
  chipLabel: { color: THEME.darkGreen, fontWeight: "600" },
  chipLabelOn: { color: THEME.white },
  filters: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },
  expirationDays: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
    marginBottom: 12,
  },
  holdControls: { opacity: 1 },
  holdControlsOff: { opacity: 0.4 },
});
